### ISSUE TITLE
invalid schema for search_api.server.pantheon_solr8.yml

### ISSUE THREAD

**Issue by dpagini** [stevector/search_api_pantheon#168]
**Describe the bug**
This is described in more detail on the [d.o issue](https://drupal.org/project/search_api_pantheon/issues/3262003) that is still open and reported the same problem. This was attempted to be fixed in #101 and #165, but neither of those are providing a full schema. The patch posted in comment 7 on the drupal.org issue, I believe, is a more appropriate way to provide the schema for this module. The module does not appear to be providing any of its own properties, so you should just be able to extend the standard connector provided by `search_api_solr`. This will also ensure that this continues to work in the future if the main module adds any properties.

```yml
plugin.plugin_configuration.search_api_solr_connector.pantheon:
  type: plugin.plugin_configuration.search_api_solr_connector.standard
  label: 'Search API Solr Pantheon connector settings'
```

**To Reproduce**
1. Write an automated (functional) test that installs `search_api_pantheon`
2. Run the automated test and observe the failure.

**Expected behavior**
Automated testing should not flag an invalid schema. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1724163/234053530-ecabed99-b2c4-48e5-97f3-f9ae8bc78623.png)

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A
